live_config_reload = true

[font]
size = 12

[window]
# full or none
decorations = "full"
dynamic_title = true
opacity = 0.95
title = "terminal"

[cursor.style]
shape = "Block"

[keyboard]
# these dont actually do anything, but they are here for reference
# for when I inevitably forget how to increase the font size.
bindings = [
  { key = "=", mods = "Control", action = "IncreaseFontSize" },
  { key = "-", mods = "Control", action = "DecreaseFontSize" },
  { key = "0", mods = "Control", action = "ResetFontSize" },
]

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Shift"

[window.dimensions]
columns = 150
lines = 42

[window.padding]
x = 5
y = 3

[colors.primary]
background='#1a1b26'
foreground='#a9b1d6'

[colors.normal]
black='#32344a'
red='#f7768e'
green='#9ece6a'
yellow='#e0af68'
blue='#7aa2f7'
magenta='#ad8ee6'
cyan='#449dab'
white='#787c99'

[colors.bright]
black='#444b6a'
red='#ff7a93'
green='#b9f27c'
yellow='#ff9e64'
blue='#7da6ff'
magenta='#bb9af7'
cyan='#0db9d7'
white='#acb0d0'

# color setup
# [colors]
# draw_bold_text_with_bright_colors = true

# # [colors.cursor]
# # cursor = "#528bff"
# # text = "CellBackground"

# [colors.dim]
# black= "#131415"
# red= "#864343"
# green= "#777c44"
# yellow= "#9e824c"
# blue= "#556a7d"
# magenta= "#75617b"
# cyan= "#5b7d78"
# white= "#828482"

# [colors.selection]
# background = "#3e4451"
# text = "CellForeground"
