version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[var]
  StagingIcon = "+"
  WorkingIcon = "!"
  UntrackedIcon = "?"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'default'
    template = '<magenta>[<blue>{{ .Path }}<magenta>@{{ .HostName }}<magenta>]'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]

    type = 'git'
    style = 'plain'
    foreground = '#darkGray'
    background = 'transparent'
    template = '<foreground> {{ .HEAD }} {{ if .Staging.Changed }}<yellow>{{ .Var.StagingIcon }}{{ add .Staging.Modified .Staging.Added .Staging.Deleted }} {{ end }}{{ if (add .Working.Modified .Working.Added .Working.Deleted) }}<yellow>{{ .Var.WorkingIcon }}{{ add .Working.Modified .Working.Added .Working.Deleted }} {{ end }}{{ if .Working.Untracked }}<cyan>{{ .Var.UntrackedIcon }}{{ .Working.Untracked }} {{ end }}<cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 500

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '
